sync on 2026/08/01, rev 698bb3e3fa39bc1995e9b6ec175af83e3687aeeb

diff --git a/prog/engine/drv/drv3d_DX12/jamfile b/prog/engine/drv/drv3d_DX12/jamfile
--- a/prog/engine/drv/drv3d_DX12/jamfile
+++ b/prog/engine/drv/drv3d_DX12/jamfile
@@ -9,12 +9,16 @@ Target      = engine/drv/drv3d_DX12.lib ;
 
 include $(Root)/prog/_jBuild/defaults.jam ;
 
-if $(Platform) in windows && $(PlatformArch) in arm64 {
-  if ! $(UseDlssInterface) && ! [ GLOB $(_DEVTOOL) : ngx-dlss-* ] { UseDlssInterface = no ; }
-  UseDlssInterface ?= yes ;
-} else {
-  UseDlssInterface = no ;
+if ! $(Platform) in windows xboxOne scarlett {
+  exit FATAL\: $(Platform) is not supported platform for drv3d_DX12 ;
 }
+
+if ! $(PlatformArch) in x86_64 arm64 {
+  exit FATAL\: $(PlatformArch) is not supported platform architecture for drv3d_DX12 ;
+}
+
+local 1stPartyDir = $(Root)/prog/1stPartyLibs ;
+local 3rdPartyDir = $(Root)/prog/3rdPartyLibs ;
 
 Sources =
   init_d3di.cpp
@@ -24,7 +28,9 @@ Sources =
   swapchain.cpp
   format_store.cpp
   device_context.cpp
+  query_manager.cpp
   synced_command_store.cpp
+  mirrored_ring_memory.cpp
   shader.cpp
   texture.cpp
   pipeline.cpp
@@ -44,23 +50,19 @@ Sources =
   ray_trace_pipeline.cpp
 ;
 
-CPPopt = -DINSIDE_DRIVER ;
-# do not include stuff that depends on wrl, including wrl is a mess
-CPPopt += -DD3DX12_NO_STATE_OBJECT_HELPERS ;
-
 AddIncludes +=
   $(Root)/prog/engine/sharedInclude
   $(Root)/prog/engine/drv/drv3d_commonCode
   $(Root)/prog/engine/drv/drv3d_DX12
   $(Root)/prog/engine/shaders
   $(Root)/prog/dagorInclude
-  $(Root)/prog/3rdPartyLibs/imgui
+  $(3rdPartyDir)/imgui
 ;
 
-if $(Platform) in windows xboxOne scarlett {
-  CPPopt += -FId3d_config.h ;
-  CPPopt += -DUSE_RESOURCE_HEAPS ;
-}
+CPPopt = -DINSIDE_DRIVER ;
+# do not include stuff that depends on wrl, including wrl is a mess
+CPPopt += -DD3DX12_NO_STATE_OBJECT_HELPERS ;
+CPPopt += -FId3d_config.h ;
 
 if $(Config) != rel {
   Sources +=
@@ -69,8 +71,6 @@ if $(Config) != rel {
     resource_usage_debugger.cpp
   ;
 }
-
-local 3rdPartyDir = $(Root)/prog/3rdPartyLibs ;
 
 if $(Platform) in windows {
   Sources +=
@@ -88,7 +88,20 @@ if $(Platform) in windows {
     debug/gpu_capture/render_doc.cpp
   ;
 
+  # for GPU crash dump sending
+  AddIncludes += $(1stPartyDir)/jsoncpp/include ;
+  UseProgLibs += 1stPartyLibs/jsoncpp ;
+
   if $(PlatformArch) = x86_64 {
+    local AftermathSdkDir = $(3rdPartyDir)/aftermath/$(AftermathSdkVer) ;
+    if [ GLOB $(AftermathSdkDir) : * ] {
+      AddIncludes += $(AftermathSdkDir)/include ;
+      CPPopt += -DHAS_GF_AFTERMATH ;
+      Sources +=
+        debug/gpu_postmortem_nvidia_aftermath.cpp
+      ;
+    }
+
     local AgsSdkDir = $(_DEVTOOL)/AGS.SDK.$(AgsSdkVer) ;
     if [ GLOB $(AgsSdkDir) : * ] && $(AgsEnabled) = yes {
       AddIncludes += $(AgsSdkDir)/inc ;
@@ -101,30 +114,27 @@ if $(Platform) in windows {
       ;
     }
 
-    if [ GLOB $(3rdPartyDir)/aftermath : * ] {
-      AddIncludes += $(3rdPartyDir)/aftermath/2025.5.0.251114/include ;
-      CPPopt += -DHAS_GF_AFTERMATH ;
-      Sources +=
-        debug/gpu_postmortem_nvidia_aftermath.cpp
-      ;
-    }
-
     AddIncludes += $(_DEVTOOL)/nvapi-$(NvApiVer) ;
     CPPopt += -DHAS_NVAPI ;
   }
 
-  if $(Config) != rel && $(PlatformArch) in arm64 x86_64 && [ GLOB $(3rdPartyDir)/winpixeventruntime : * ] {
-    AddIncludes += $(3rdPartyDir)/winpixeventruntime/Include/WinPixEventRuntime ;
+  local WinPixEventRuntimeDir = $(3rdPartyDir)/winpixeventruntime ;
+  if $(Config) != rel && [ GLOB $(WinPixEventRuntimeDir) : * ] {
+    local ArchName = x64 ;
     if $(PlatformArch) = arm64 {
-      AddLibs += $(3rdPartyDir)/winpixeventruntime/bin/ARM64/WinPixEventRuntime.lib ;
-    } else if $(PlatformArch) = x86_64 {
-      AddLibs += $(3rdPartyDir)/winpixeventruntime/bin/x64/WinPixEventRuntime.lib ;
+      ArchName = ARM64 ;
     }
-    AddLibs += delayimp.lib -delayload:WinPixEventRuntime.dll ;
+
+    AddIncludes += $(WinPixEventRuntimeDir)/Include/WinPixEventRuntime ;
+    AddLibs +=
+      $(WinPixEventRuntimeDir)/bin/$(ArchName)/WinPixEventRuntime.lib
+      delayimp.lib
+      -delayload:WinPixEventRuntime.dll
+    ;
     CPPopt += -DUSE_PIX -DPIX_USE_GPU_MARKERS_V2 ;
     Sources += debug/gpu_capture/pix.cpp ;
   }
-} else if $(Platform) in xboxOne scarlett {
+} else {
   CPPopt += /wd4062 ; # enumerator 'XXX' in switch of enum 'YYY' is not handled
   if $(Config) != rel {
     AddLibs += PIXEvt.lib ;
@@ -133,50 +143,59 @@ if $(Platform) in windows {
   if $(Platform) = xboxOne {
     AddLibs += d3d12_x.lib xg_x.lib ;
   } else {
-    Sources += shader_library.cpp ;
     AddLibs += d3d12_xs.lib xg_xs.lib ;
+    Sources += shader_library.cpp ;
   }
-  Sources +=
-    platform_xbox.cpp
-  ;
+  Sources += platform_xbox.cpp ;
 }
 
-if $(XessEnabled) = yes && $(Platform)-$(PlatformArch) = windows-x86_64 && [ GLOB $(3rdPartyDir)/xess_sdk : * ] {
+# Upscalers: each has a stub implementation for the platforms without its SDK.
+if $(Platform)-$(PlatformArch) = windows-x86_64 {
+  local FidelityFXSDKDir = $(_DEVTOOL)/FidelityFX-SDK-$(FidelityFXVer) ;
+
+  if ! [ GLOB $(FidelityFXSDKDir) : * ] { exit FATAL\: \"$(FidelityFXSDKDir)\" not found!  Please, update DEVTOOLS ; }
+
+  AddIncludes +=
+    $(FidelityFXSDKDir)/Kits/FidelityFX
+    $(FidelityFXSDKDir)/Kits/FidelityFX/api/include
+    $(FidelityFXSDKDir)/Kits/FidelityFX/framegeneration/include
+    $(FidelityFXSDKDir)/Kits/FidelityFX/upscalers/include
+  ;
+  Sources +=
+    amdFsrD3D12_windows.cpp
+    fsr_wrapper.cpp
+   ;
+} else if $(Platform) in xboxOne scarlett {
+  AddIncludes += $(3rdPartyDir)/fsr3.1.3_xbox/include ;
+  Sources +=
+    amdFsrD3D12_xbox.cpp
+    fsr_wrapper.cpp
+  ;
+} else {
+  Sources += fsr_wrapper_stub.cpp ;
+}
+
+DlssVersion   ?= 310.3.0 ;
+
+local NgxDir = $(_DEVTOOL)/ngx-dlss-$(DlssVersion) ;
+if $(Platform)-$(PlatformArch) = windows-arm64  && [ GLOB $(NgxDir) : * ] {
+  AddIncludes += $(NgxDir)/include ;
+  AddLibs += $(NgxDir)/lib/Windows_$(PlatformArch)/nvsdk_ngx_s.lib ;
+  CPPopt += -DUSE_DLSS_WITHOUT_STREAMLINE ;
+  Sources += dlss.cpp ;
+} else {
+  Sources += dlss_stub.cpp ;
+}
+
+if $(Platform)-$(PlatformArch) = windows-x86_64 && $(XessEnabled) = yes && [ GLOB $(3rdPartyDir)/xess_sdk : * ] {
   Target = $(Target:S=~xess.lib) ;
   Sources += xess_wrapper.cpp ;
 } else {
   Sources += xess_wrapper_stub.cpp ;
 }
 
-if $(Fsr2Enabled) = yes && $(Platform)-$(PlatformArch) = windows-x86_64 {
-  Target = $(Target:S=~fsr2.lib) ;
-  Sources += fsr2_wrapper.cpp ;
-  UseProgLibs += 3rdPartyLibs/fsr2 ;
-} else {
-  Sources += fsr2_wrapper_stub.cpp ;
-}
-
-if $(Platform)-$(PlatformArch) = windows-x86_64 {
-  local FidelityFXSDKDir = $(_DEVTOOL)/FidelityFX-SDK-$(FidelityFXVer)/Kits/FidelityFX ;
-
-  if ! [ GLOB $(_DEVTOOL)/FidelityFX-SDK-$(FidelityFXVer) : * ] { exit FATAL\: \"$(_DEVTOOL)/FidelityFX-SDK-$(FidelityFXVer)\" not found!  Please, update DEVTOOLS ; }
-
-  Sources += amdFsrD3D12_windows.cpp fsr_wrapper.cpp ;
-  AddIncludes +=
-    $(FidelityFXSDKDir)
-    $(FidelityFXSDKDir)/api/include
-    $(FidelityFXSDKDir)/framegeneration/include
-    $(FidelityFXSDKDir)/upscalers/include
-  ;
-}
-else if $(Platform) in xboxOne scarlett {
-  Sources += amdFsrD3D12_xbox.cpp fsr_wrapper.cpp ;
-  AddIncludes += $(3rdPartyDir)/fsr3.1.3_xbox/include ;
-}
-else {
-  Sources += fsr_wrapper_stub.cpp ;
-}
-
+# The Agility SDK provides d3d12.h and has to precede the Windows SDK on the command line,
+# hence pre_opt. Keep this after every source was added, it binds the current $(Sources).
 if $(Platform) in windows {
   local AgilitySdkDir = $(_DEVTOOL)/Agility.SDK.$(AgilitySdkVer) ;
 
@@ -185,30 +204,6 @@ if $(Platform) in windows {
   pre_opt on $(Sources) = -I$(AgilitySdkDir)/include ;
 
   AddIncludes += $(AgilitySdkDir)/include/d3dx12 ;
-}
-
-# for GPU crash dump sending
-if $(Platform) in windows {
-  UseProgLibs +=
-    1stPartyLibs/jsoncpp ;
-
-  AddIncludes += $(Root)/prog/1stPartyLibs/jsoncpp/include ;
-}
-
-if $(UseDlssInterface) = yes {
-  if $(PlatformArch) in arm64 {
-    DlssVersion ?= 310.3.0 ;
-  }
-  DlssVersion ?= 310.5.3 ;
-  if ! [ GLOB $(_DEVTOOL)/ngx-dlss-$(DlssVersion) : * ] { exit FATAL\: \"$(_DEVTOOL)/ngx-dlss-$(DlssVersion)\" not found!  Please, update DEVTOOLS ; }
-
-  CPPopt += -DUSE_DLSS_WITHOUT_STREAMLINE ;
-  AddIncludes += $(_DEVTOOL)/ngx-dlss-$(DlssVersion)/include ;
-  Sources += dlss.cpp ;
-
-  AddLibs += $(_DEVTOOL)/ngx-dlss-$(DlssVersion)/lib/Windows_$(PlatformArch)/nvsdk_ngx_s.lib ;
-} else {
-  Sources += dlss_stub.cpp ;
 }
 
 UseProgLibs +=
